### PR TITLE
Phood 7 display array of recipes

### PR DESCRIPTION
**Pull request by TWeiss21**

### CODE REVIEW

**Review by comessErinaceus — DISMISSED** [review]
Looks like you have the info displaying from the json mock data. Could you only use the names of recipes instead of the descriptions?

**Review by FawnGuardian — DISMISSED** [review]
Refer to Discord message for changes.

**Review by FawnGuardian — APPROVED** [review]
we did the things to make it work :)

**Review by steverc9434 — APPROVED** [review]
Neato

**Pull request merged**
